spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:3306/student_registration_db
    username: root
    password: 0936
  jpa:
    hibernate:
      ddl-auto: update
