apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-approval-d
spec:
  selector:
    matchLabels:
      app: driver-approval-p
  replicas: 2
  template:
    metadata:
      labels:
        app: driver-approval-p
    spec:
      containers:
        - name: driver-approval-c
          image: driver-approval:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-db-s:3306/driver_approval_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: "0936"
            - name: SERVER_PORT
              value: "8081"
