apiVersion: v1
kind: Service
metadata:
  name: student-registration-s
spec:
  type: LoadBalancer
  selector:
    app: student-registration-p
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080