apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-registration-d
spec:
  selector:
    matchLabels:
      app: student-registration-p
  replicas: 1
  template:
    metadata:
      labels:
        app: student-registration-p
    spec:
      containers:
        - name: student-registration-c
          image: student-registration:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
