apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-registration-d
spec:
  selector:
    matchLabels:
      app: student-registration-p
  replicas: 1
  template:
    metadata:
      labels:
        app: student-registration-p
    spec:
      containers:
        - name: student-registration-c
          image: student-registration:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-db-s:3306/student_registration_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: "0936"
            - name: SERVER_PORT
              value: "8080"
