apiVersion: apps/v1
kind: Deployment
metadata:
  name: sr-service
spec:
  selector:
    matchLabels:
      app: sr-service
  replicas: 1
  template:
    metadata:
      labels:
        app: sr-service
    spec:
      containers:
        - name: sr-service
          image: student-registration:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
