apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-service-d
spec:
  selector:
    matchLabels:
      app: trips-service-p
  replicas: 1
  template:
    metadata:
      labels:
        app: trips-service-p
    spec:
      containers:
        - name: trips-service-c
          image: trips-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-db-s:3306/trips_service_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: "0936"
            - name: SERVER_PORT
              value: "8082"
